# Metadata about this component, to be used in the CMS
spec:
  structures:
    - buttons
  label: Secondary Button
  description: "Outline & transparent bg"
  icon: "smart_button"
  tags:
    - Outline
    - Transparent background

# Defines the structure of this component, as well as the default values
blueprint:
  button_text:
  button_icon:
  button_link: 
  button_aria_label:
  background_color: "#034AD8"
  hover_brightness: 0.85
  text_color: "#ffffff"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:

