# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Left-Right
  description: Text next to image
  icon: "chrome_reader_mode"
  tags:
    - Image
    - Text
    - Button

# Defines the structure of this component, as well as the default values
blueprint:
  background_color: "#ffffff"
  flipped: true
  heading:
    heading_text: 
    text_color: "#333232"
  text:
    text_content:
    text_color: "#333232"
  image:
    image_path: 
    alt_text: 
  button:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  flipped:
    type: switch
  heading:
    options:
      preview:
        icon: 'short_text'
        text:
          - key: heading_text
          - Heading
        subtext:
          - Update heading text and color
  text:
    options:
      preview:
        icon: 'description'
  image:
    options:
      preview:
        icon: 'image'
        text:
          - key: alt_text
          - 'Image'
        subtext:
          - key: image_path
          - 'Update image'
        image:
          - key: image_path
  button:
    type: object
    options:
      structures: _structures.buttons